# Generated by Django 2.2.5 on 2020-02-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_justificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljustificacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Auditoria', 'En proceso de auditoria'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Anulado por Marcaje', 'Anulado por Marcaje')], default='Pendiente', max_length=25),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Auditoria', 'En proceso de auditoria'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Anulado por Marcaje', 'Anulado por Marcaje')], default='Pendiente', max_length=25),
        ),
    ]
