# Generated by Django 2.2.5 on 2019-10-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_justificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificacion',
            name='estado',
            field=models.CharField(choices=[('Pe', 'Pendiente'), ('Au', 'En proceso de auditoria'), ('Ap', 'Aprobado'), ('Rc', 'Rechazado')], default='Pe', max_length=2),
        ),
    ]
