# Generated by Django 2.2.5 on 2019-10-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_justificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificacion',
            name='fecha_solicitud',
            field=models.DateField(auto_now=True),
        ),
    ]
