# Generated by Django 2.2.5 on 2019-10-07 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_justificacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_tipojustificacion', '0003_auto_20191007_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='justificacion',
            name='legajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='justificacion',
            name='tipo_justificacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app_tipojustificacion.TipoJustificacion'),
        ),
    ]
