# Generated by Django 2.2.5 on 2019-10-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_justificacion', '0003_historicaljustificacion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicaljustificacion',
            table='justificacion_historial',
        ),
    ]
