# Generated by Django 2.2.5 on 2019-10-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_justificacion', '0003_auto_20191002_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Auditoria', 'En proceso de auditoria'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=16),
        ),
    ]
