# Generated by Django 2.2.5 on 2019-10-07 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_justificacion', '0003_justificacion_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificacion',
            name='fecha_solicitud',
            field=models.DateField(default=datetime.datetime(2019, 10, 7, 4, 42, 24, 615154, tzinfo=utc)),
        ),
    ]
