# Generated by Django 2.2.5 on 2019-10-07 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_justificacion', '0004_auto_20191007_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificacion',
            name='fecha_solicitud',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
