# Generated by Django 2.2.5 on 2019-10-07 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_justificacion', '0005_auto_20191007_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificacion',
            name='tipo_justificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_tipojustificacion.TipoJustificacion'),
        ),
    ]
