# Generated by Django 2.1 on 2019-09-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('requisitos', models.CharField(max_length=200)),
                ('horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoJustificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('artcct', models.CharField(max_length=200)),
                ('se_lista', models.BooleanField()),
                ('dia_trabajado', models.BooleanField()),
                ('cant_mes', models.IntegerField()),
                ('cant_año', models.IntegerField()),
                ('claustro', models.CharField(max_length=1)),
                ('borrado', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='tipo_justificacion',
            field=models.ManyToManyField(to='app_tipojustificacion.TipoJustificacion'),
        ),
    ]
