# Generated by Django 2.2.5 on 2019-09-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tipojustificacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipojustificacion',
            name='borrado',
        ),
    ]
