# Generated by Django 2.2.5 on 2019-09-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tipojustificacion', '0002_remove_tipojustificacion_borrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipojustificacion',
            name='se_lista',
        ),
    ]
