# Generated by Django 2.2.5 on 2019-10-25 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_tipojustificacion', '0004_auto_20191009_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTipoJustificacion',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('motivo', models.CharField(max_length=200)),
                ('artcct', models.CharField(max_length=200)),
                ('dia_trabajado', models.BooleanField()),
                ('cant_mes', models.IntegerField()),
                ('cant_año', models.IntegerField()),
                ('claustro', models.CharField(choices=[('Docente', 'Docente'), ('No Docente', 'No Docente')], max_length=11)),
                ('cargo', models.CharField(choices=[('A02 ', 'A02-366'), ('A-09', 'A09-2213'), ('A11 ', 'A10'), ('A10 ', 'A10'), ('A03 ', 'A3-366'), ('ADJ ', 'ADJUNTO'), ('AT1 ', 'ASISTENTE TECNICO 1'), ('AT2 ', 'ASISTENTE TECNICO 2'), ('AT3 ', 'ASISTENTE TECNICO 3'), ('AT4 ', 'ASISTENTE TECNICO 4'), ('ASOC', 'ASOCIADO'), ('AUX ', 'AUX'), ('7   ', 'AUXILIAR'), ('AYSI', 'Ayudante de Docencia'), ('AYPA', 'Ayudante de Docencia'), ('AY1 ', 'Ayudante de Primera'), ('B2  ', 'BECA 2'), ('BEC1', 'Beca tipo 1'), ('BEC2', 'Beca tipo 2'), ('BEC3', 'Beca tipo 3'), ('01  ', 'CATEGORIA 01'), ('02  ', 'CATEGORIA 02'), ('03  ', 'CATEGORIA 03'), ('04  ', 'CATEGORIA 04'), ('05  ', 'CATEGORIA 05'), ('06  ', 'CATEGORIA 06'), ('07  ', 'CATEGORIA 07'), ('207 ', 'CATEGORIA 7'), ('CA1 ', 'CONSULTOR A 1'), ('CA2 ', 'CONSULTOR A 2'), ('CA3 ', 'CONSULTOR A 3'), ('CA4 ', 'CONSULTOR A 4'), ('CB1 ', 'CONSULTOR B 1'), ('CB2 ', 'CONSULTOR B 2'), ('CB3 ', 'CONSULTOR B 3'), ('CB4 ', 'CONSULTOR B 4'), ('CC1 ', 'CONSULTOR C 1'), ('CC2 ', 'CONSULTOR C 2'), ('CC3 ', 'CONSULTOR C 3'), ('CC4 ', 'CONSULTOR C 4'), ('CD1 ', 'CONSULTOR D 1'), ('CD2 ', 'CONSULTOR D 2'), ('CD3 ', 'CONSULTOR D 3'), ('CD4 ', 'CONSULTOR D 4'), ('cono', 'CONTRATO DE OBRA'), ('CG1 ', 'COORDINADOR GRAL 1'), ('CG2 ', 'COORDINADOR GRAL 2'), ('CG3 ', 'COORDINADOR GRAL 3'), ('CA  ', 'Consultor A'), ('CB  ', 'Consultor B'), ('CC  ', 'Consultor C'), ('CD  ', 'Consultor D'), ('E0  ', 'Contrato 1190'), ('PAU1', 'DIRECTOR GENERAL'), ('S76 ', 'Director Ejecutivo'), ('EPUA', 'EPU CATEGORIA"A"'), ('H030', 'Horas Catedra 030'), ('JTP1', 'JEFE TRAB. PRACTICOS'), ('JEFE', 'JTP'), ('JTP ', 'JTP'), ('0   ', 'JTP Ad-Honorem'), ('3   ', 'Jefe de Cátedra'), ('220 ', 'Jefe de División'), ('jtp ', 'Jefe de Trab. Prácti'), ('S73 ', 'Ministro'), ('SA  ', 'Ministros Plenipoten'), ('AV  ', 'PAU'), ('PAU0', 'Personal de Apoyo Un'), ('PREC', 'Preseptoría'), ('A   ', "SINAPA 'A'"), ('B   ', "SINAPA 'B'"), ('C   ', "SINAPA 'C'"), ('D   ', "SINAPA 'D'"), ('E   ', "SINAPA 'E'"), ('F   ', "SINAPA 'F'"), ('S74 ', 'Secretario'), ('S75 ', 'SubSecretario'), ('STF ', 'Suplente Termino Fij'), ('TIT ', 'TITULAR'), ('b1  ', 'beca sergio'), ('A07 ', 'cat A07'), ('A62 ', 'kaslnmkoanc'), ('5   ', 'nomse'), ('extr', 'prof. extraordinario')], max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tipo justificacion',
                'db_table': 'tjustificacion_historial',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
