# Generated by Django 2.2.5 on 2020-01-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tipojustificacion', '0010_auto_20191204_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltipojustificacion',
            name='cargo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tipojustificacion',
            name='cargo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
