# Generated by Django 2.2.5 on 2020-01-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tipojustificacion', '0012_auto_20200123_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltipojustificacion',
            name='cargo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tipojustificacion',
            name='cargo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
