# Generated by Django 2.2.5 on 2019-11-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
