# Generated by Django 2.2.5 on 2020-01-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0005_auto_20200120_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosfijos',
            name='hora_salida',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horariosfijos',
            name='horas_a_cumplir',
            field=models.TimeField(),
        ),
    ]
