# Generated by Django 2.2.5 on 2020-01-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0003_auto_20200125_0801'),
        ('app_horarios', '0006_auto_20200123_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallehorario',
            name='cargo',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.PROTECT, to='cargos.CargosCache'),
            preserve_default=False,
        ),
    ]
