# Generated by Django 2.2.5 on 2020-01-02 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0009_historicaldetallehorario_historicalhorario_historicalhorariosfijos_historicalperiodolectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalhorario',
            name='legajo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horario',
            name='legajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
