# Generated by Django 2.2.5 on 2020-01-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargosCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_cod', models.IntegerField()),
                ('categoria', models.CharField(max_length=200)),
                ('desc_regional', models.CharField(max_length=200)),
                ('desc_categ', models.CharField(max_length=200)),
                ('desc_dedic', models.CharField(max_length=200)),
                ('horas_dedicacion', models.IntegerField()),
                ('escalafon', models.CharField(max_length=200)),
            ],
        ),
    ]
