# Generated by Django 2.2.5 on 2020-01-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoscache',
            name='seleccionado',
            field=models.BooleanField(default=False),
        ),
    ]
