# Generated by Django 2.2.5 on 2020-01-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_cargoscache_seleccionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoscache',
            name='horas_dedicacion',
            field=models.FloatField(),
        ),
    ]
