# Generated by Django 2.2.5 on 2020-01-27 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargos', '0003_auto_20200125_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoscache',
            name='agente',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
