# Generated by Django 2.2.5 on 2019-11-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
