# Generated by Django 2.2.5 on 2020-01-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0002_cargoscache_seleccionado'),
        ('login', '0002_auto_20191116_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cargos_cache',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cargos.CargosCache'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcustomuser',
            name='cargos_cache',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cargos.CargosCache'),
        ),
    ]
