# Generated by Django 2.2.5 on 2020-01-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200120_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cargos_cache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cargos.CargosCache'),
        ),
    ]
