# Generated by Django 2.2.5 on 2019-11-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_config', models.CharField(max_length=200)),
                ('valor_config', models.FloatField()),
                ('tipo_dato_config', models.CharField(max_length=200)),
            ],
        ),
    ]
