# Generated by Django 2.2.5 on 2020-01-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciones',
            name='horario_entrada_nodoc',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
