# Generated by Django 2.2.5 on 2019-11-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalasistencia',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
