# Generated by Django 2.2.5 on 2020-03-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='condicion',
            field=models.CharField(choices=[('Inasistencia Injustificada', 'Inasistencia Injustificada'), ('Inasistencia Justificada', 'Inasistencia Justificada'), ('Inconsistencia Marcaje', 'Inconsistencia Marcaje'), ('Correccion Inconsistencia', 'Correccion Inconsistencia'), ('Anulacion por Marcaje', 'Anulacion por Marcaje'), ('Marcaje Válido', 'Marcaje Válido'), ('Horas a Favor', 'Horas a Favor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalasistencia',
            name='condicion',
            field=models.CharField(choices=[('Inasistencia Injustificada', 'Inasistencia Injustificada'), ('Inasistencia Justificada', 'Inasistencia Justificada'), ('Inconsistencia Marcaje', 'Inconsistencia Marcaje'), ('Correccion Inconsistencia', 'Correccion Inconsistencia'), ('Anulacion por Marcaje', 'Anulacion por Marcaje'), ('Marcaje Válido', 'Marcaje Válido'), ('Horas a Favor', 'Horas a Favor')], max_length=50),
        ),
    ]
