# Generated by Django 2.2.5 on 2019-11-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_auto_20191101_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='condicion',
            field=models.CharField(choices=[('Asistencia', 'Asistencia'), ('Inasistencia Injustificada', 'Inasistencia Injustificada'), ('Inasistencia Justificada', 'Inasistencia Justificada'), ('Inconsistencia Marcaje', 'Inconsistencia Marcaje'), ('Correccion Inconsistencia', 'Correccion Inconsistencia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalasistencia',
            name='condicion',
            field=models.CharField(choices=[('Asistencia', 'Asistencia'), ('Inasistencia Injustificada', 'Inasistencia Injustificada'), ('Inasistencia Justificada', 'Inasistencia Justificada'), ('Inconsistencia Marcaje', 'Inconsistencia Marcaje'), ('Correccion Inconsistencia', 'Correccion Inconsistencia')], max_length=50),
        ),
    ]
